server:
  port: 8887
  address: 0.0.0.0

spring:
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/soul-dev-master-20190410?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&failOverReadOnly=false&autoReconnect=true
    username: root
    password: root
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
  zookeeper:
    url: localhost:2181
    sessionTimeout: 5000
    connectionTimeout: 2000
  redis:
    #password: foobaredbbexONE123
    timeout: 300000ms
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:26479
        - 127.0.0.1:26579
        - 127.0.0.1:26679

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    root: debug
    org.springframework.boot: debug
    org.apache.ibatis: debug
    org.dromara.soul.bonuspoint: debug
    org.dromara.soul.lottery: debug
    org.dromara.soul: debug

  path: "./logs/admin"